version: '3'

services:
  springapp:
    build: .
    ports:
      - "12345:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "12346:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "12347:3000"
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter
    ports:
      - "12348:9100"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
