global:
  scrape_interval: 10s # 10초 마다 Metric을 Pulling
  evaluation_interval: 10s # rule 을 얼마나 빈번하게 검증하는지 설정

scrape_configs:
  - job_name: 'springapp'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'springapp:8080' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]
